# Generated by Django 5.2.10 on 2026-01-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
