# Generated by Django 5.2.10 on 2026-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_attendancelog_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('LEAVE', 'Authorized Leave')], default='ABSENT', max_length=20),
        ),
    ]
