# Generated by Django 5.2.10 on 2026-03-19 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancelog_confidence_alter_attendancelog_status'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='routine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.routine'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
