# Generated by Django 5.2.10 on 2026-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancesession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='detection_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='last_detected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='out_of_frame_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='total_presence_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('LEAVE', 'Authorized Leave'), ('PARTIAL', 'Partial Presence')], default='ABSENT', max_length=20),
        ),
    ]
