# Generated by Django 5.2.10 on 2026-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancelog_detection_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='attended_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='minute_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='minute_presence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
