# Generated by Django 5.2.10 on 2026-06-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancelog_attended_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
