# Generated by Django 5.2.10 on 2026-06-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_systemconfiguration_auto_stop_minutes_and_more'),
        ('attendance', '0010_attendancesession_department_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Whether student was validated for this semester'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='session_semester',
            field=models.IntegerField(blank=True, help_text='Session semester', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='session_year',
            field=models.IntegerField(blank=True, help_text='Session year', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='student_semester',
            field=models.IntegerField(blank=True, help_text="Student's semester at time of attendance", null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='student_year',
            field=models.IntegerField(blank=True, help_text="Student's year at time of attendance", null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='validation_error',
            field=models.TextField(blank=True, help_text='Validation error message if any', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['session', 'student'], name='attendance__session_acbbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['status', 'session'], name='attendance__status_e2f46e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['is_validated'], name='attendance__is_vali_597e48_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student_semester', 'session_semester'], name='attendance__student_0af8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student', 'session_semester'], name='attendance__student_c6bbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_id'], name='attendance__session_471a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['semester', 'year'], name='attendance__semeste_aaf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_34d6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date'], name='attendance__date_38d33c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['department', 'semester', 'year'], name='attendance__departm_7ddf23_idx'),
        ),
    ]
