# Generated by Django 5.2.10 on 2026-07-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_systemconfiguration_auto_stop_minutes_and_more'),
        ('attendance', '0011_alter_attendancesession_options_and_more'),
        ('dashboard', '0002_routine_created_at_routine_duration_routine_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if session was manually created by user (shows in template)'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['is_manual'], name='attendance__is_manu_2d09ad_idx'),
        ),
    ]
