# Generated by Django 5.2.10 on 2026-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancesession_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for manual attendance change (e.g., Approved leave, Technical issue)', null=True),
        ),
    ]
