# Generated by Django 5.2.10 on 2026-07-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendancesession_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='reason',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for manual attendance change (e.g., Approved leave, Technical issue)', null=True),
        ),
    ]
