# Generated by Django 5.2.10 on 2026-02-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
