# Generated by Django 5.2.10 on 2026-02-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile_address_student_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
    ]
