# Generated by Django 5.2.10 on 2026-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='deleted_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
