# Generated by Django 5.2.10 on 2026-02-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_systemlog_deleted_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
