# Generated by Django 5.2.10 on 2026-02-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_staffprofile_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='staff_id',
        ),
    ]
