# Generated by Django 5.2.10 on 2026-02-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_staffprofile_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
