# Generated by Django 5.2.10 on 2026-03-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_threshold', models.FloatField(default=0.6)),
                ('min_retention_required', models.PositiveIntegerField(default=80, help_text='Percentage of class time required to be marked PRESENT')),
                ('institution_name', models.CharField(default='Far Western University', max_length=255)),
            ],
        ),
    ]
