# Generated by Django 5.2.10 on 2026-03-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_systemconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfiguration',
            options={'verbose_name': 'System Configuration', 'verbose_name_plural': 'System Configuration'},
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='alert_email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='attendance_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='auto_stop_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='cache_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='camera_source',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='debug_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='detection_model',
            field=models.CharField(default='hog', max_length=20),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_api',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='frame_resolution',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='frame_skip',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='log_retention_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='notify_low_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='notify_session_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='notify_session_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='processing_threads',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='require_api_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='timezone',
            field=models.CharField(default='Asia/Kathmandu', max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='upsample_factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='institution_name',
            field=models.CharField(default='Far Western University', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='min_retention_required',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='recognition_threshold',
            field=models.FloatField(default=0.65),
        ),
    ]
