# Generated by Django 5.2.10 on 2026-03-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_systemconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='api_key',
            field=models.CharField(blank=True, help_text='Auto-generated API key', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='attendance_threshold',
            field=models.IntegerField(default=50, help_text='Low attendance alert threshold %'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='auto_stop_minutes',
            field=models.IntegerField(default=5, help_text='Auto-stop after N minutes of no detection'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='cache_size',
            field=models.IntegerField(default=100, help_text='Number of face encodings to keep in RAM'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='camera_source',
            field=models.CharField(default='0', help_text='0=built-in, 1=external, or RTSP URL', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='debug_mode',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Basic Logging'), (2, 'Verbose Logging')], default=0, help_text='Debug logging level'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_duration',
            field=models.IntegerField(default=60, help_text='Default session duration in minutes'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='detection_model',
            field=models.CharField(choices=[('hog', 'HOG (Fast, CPU)'), ('cnn', 'CNN (Slow, GPU)')], default='hog', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='enable_api',
            field=models.BooleanField(default=True, help_text='Enable REST API'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='frame_resolution',
            field=models.FloatField(choices=[(0.5, '640x480 (Fast)'), (0.75, '960x720 (Balanced)'), (1.0, '1280x720 (HD)')], default=0.75),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='frame_skip',
            field=models.IntegerField(choices=[(1, 'Every Frame (Max CPU)'), (3, 'Every 3rd Frame (Recommended)'), (5, 'Every 5th Frame (Eco)')], default=3),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='log_retention_days',
            field=models.IntegerField(default=30, help_text='Days to keep attendance logs'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='min_retention_required',
            field=models.IntegerField(default=80, help_text='Percentage to be marked PRESENT'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='processing_threads',
            field=models.IntegerField(choices=[(1, '1 Thread (Low CPU)'), (2, '2 Threads (Balanced)'), (4, '4 Threads (High Performance)')], default=2),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='recognition_threshold',
            field=models.FloatField(default=0.65, help_text='Lower = stricter (0.3-0.9)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='require_api_key',
            field=models.BooleanField(default=False, help_text='Require API key for access'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='rtsp_url',
            field=models.CharField(blank=True, help_text="Required if camera_source='rtsp'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='upsample_factor',
            field=models.IntegerField(choices=[(0, '0 (Fastest)'), (1, '1 (Balanced)'), (2, '2 (Best Quality)')], default=1),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Send attendance data to external system'),
        ),
    ]
