# Generated by Django 5.2.10 on 2026-04-25 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_systemconfiguration_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_push_notifications',
            field=models.BooleanField(default=True, help_text='Enable push notifications'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='notification_duration',
            field=models.IntegerField(default=5, help_text='Notification display duration in seconds'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='notification_sound',
            field=models.BooleanField(default=True, help_text='Play sound for notifications'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance Marked'), ('session', 'Session Event'), ('student', 'Student Registration'), ('staff', 'Staff Registration'), ('alert', 'Security Alert'), ('proxy', 'Proxy Detection'), ('system', 'System Update'), ('recognition', 'Face Recognition'), ('reminder', 'Reminder'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx'), models.Index(fields=['is_read', '-created_at'], name='accounts_no_is_read_78f484_idx'), models.Index(fields=['notification_type', '-created_at'], name='accounts_no_notific_681bde_idx')],
            },
        ),
    ]
