# Generated by Django 5.2.10 on 2026-06-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_systemconfiguration_enable_push_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='deleted_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('register', 'Register'), ('login_failed', 'Login Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-timestamp'], name='accounts_sy_timesta_5e1b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', 'action'], name='accounts_sy_user_id_8c21a4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['is_deleted'], name='accounts_sy_is_dele_31e10c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['ip_address'], name='accounts_sy_ip_addr_054df1_idx'),
        ),
    ]
