# Generated by Django 5.2.10 on 2026-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_systemlog_deleted_at_systemlog_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='auto_stop_minutes',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_duration',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='max_gap_seconds',
            field=models.IntegerField(default=30, help_text='Maximum seconds gap before counting as out of frame'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='partial_retention_threshold',
            field=models.IntegerField(default=50, help_text='Minimum retention percentage for PARTIAL status'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='min_retention_required',
            field=models.IntegerField(default=80, help_text='Minimum retention percentage to be marked PRESENT'),
        ),
    ]
